// @prepros-append source/start.js
// @prepros-append source/initialization.js
// @prepros-append source/phone-mask.js
// @prepros-append source/check-form.js
// @prepros-append source/edit-wp7.js
// @prepros-append source/img-cover.js
// @prepros-append source/style-file.js
// @prepros-append source/style-select.js
// @prepros-append source/search-ajax.js
// @prepros-append source/search-ajax-input.js
// @prepros-append source/btn-show-hide.js
// @prepros-append source/password-edit.js
// @prepros-append source/simple.js
// @prepros-append source/tabs.js
// @prepros-append source/rating-comments.js
// @prepros-append source/end.js